- name: create group node-exporter
  group:
    name: "node-exporter"
    system: true
    state: present

- name: create user node-exporter
  user:
    name: node-exporter
    groups: node-exporter
    append: true
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: check if node-exporter exist
  stat:
    path: /usr/local/bin/node-exporter
  register: _svc_node_exporter

- name: download and install node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz
    dest: /tmp/
    remote_src: yes
    mode: 0755
  delegate_to: localhost
  when: _svc_node_exporter.stat.exists == false
  check_mode: false

- name: push node-exporter binary
  copy:
    src: /tmp/node_exporter-0.18.1.linux-armv7/node_exporter
    dest: /usr/local/bin/node-exporter
    mode: 0755
    owner: node-exporter
    group: node-exporter
  when: _svc_node_exporter.stat.exists == false

- name: create systemd service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: 0644
  notify: restart_node_exporter

- name:
  service:
    name: node-exporter
    state: started
