- name: deploy users
  become: yes
  hosts: all
  roles:
  - users
  - firewalls
  - monitoring-custom
  - etc-hosts
  - node-exporter

- name: monitoring-gui
  become: yes
  hosts: monitoring-gui
  roles:
  - prometheus
  - grafana

- name: install front haproxy
  become: yes
  hosts: haproxy
  roles:
  - haproxy
  - letsencrypt
  tags:
  - cert
