- name: deploy users
  become: yes
  hosts: all
  roles:
  - users
  - firewalls
  - monitoring-custom
  - etc-hosts

- name: monitoring-gui
  become: yes
  hosts: monitoring-gui
  roles:
  - prometheus
  - grafana
