all:
  children:
    door:
      hosts:
        pidoor:
          ansible_host: 192.168.1.31
          bastion: true
    back:
      hosts:
        pi1:
          ansible_host: 192.168.1.41
        pi2:
          ansible_host: 192.168.1.42
        pi3:
          ansible_host: 192.168.1.43
      children:
        prometheus:
          hosts:
            pi4:
              ansible_host: 192.168.1.44
