- name: install utils
  apt:
    name:
      - curl
      - wget
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: check if grafana exist
  stat:
    path: /etc/init.d/grafana-server
  register: _svc_grafana

- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-rpi_6.5.1_armhf.deb
    dest: /tmp/grafana-rpi_6.5.1_armhf.deb
  when: _svc_grafana.stat.exists == false

- name: install .deb using dpkg
  apt:
    deb: /tmp/grafana-rpi_6.5.1_armhf.deb
    state: installed
  when: _svc_grafana.stat.exists == false

- name: set config file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: grafana_restart

- name: start grafana
  service:
    name: grafana-server
    state: started
