users_password_xavki: "{{ vault_users_password_xavki }}"
users_password_xavier: "{{ vault_users_password_xavier }}"
users_admin:
- { name: "xavki", password: "{{ vault_users_password_xavki }}" }
users_no_admin:
- { name: "xavier", password: "{{ vault_users_password_xavier }}" }

