#!/bin/bash
# printMetric name description type value
function printMetric {
    echo "# HELP $1 $2"
    echo "# TYPE $1 $3"
    echo "$1 $4"
}

TEMPERATURE=$(vcgencmd measure_temp | sed s/\'C//g | sed s/temp=//g)
printMetric "pi_temperature" "Temperature from raspberry in celsius" "counter" $TEMPERATURE
