
- name: install haproxy
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: haproxy
    state: present

- name: add haproxy.cfg file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: haproxy_reload
